/**
 * SHAP Explainability Workspace Component Controller
 * Repository: seucra/vulnarability-prioritization-triage-system
 */

import { api } from '../api.js';
import { state } from '../state.js';

export function renderExplanationView(containerEl) {
    containerEl.innerHTML = `
        <div class="section-header">
            <div>
                <h2 class="section-title">Model Explainability Workspace</h2>
                <p class="section-desc">Inspects local feature attributions generated by TreeExplainer for frozen gradient boosted trees across EXP-A1 and EXP-B2.</p>
            </div>
            <div class="segmented-control" id="explain-mode-toggle" style="align-self: flex-start;">
                <button class="segmented-item active" id="tab-explain-cvss" type="button">EXP-A1 · CVSS Regressor</button>
                <button class="segmented-item" id="tab-explain-kev" type="button">EXP-B2 · KEV Classifier</button>
            </div>
        </div>

        <div class="workspace-grid" style="grid-template-columns: 1.05fr 0.95fr; gap: 24px; align-items: start;">
            <!-- Form Card -->
            <div class="card">
                <div class="card-header" style="padding-bottom: 12px; margin-bottom: 18px; border-bottom: 1px solid var(--border-subtle);">
                    <h3 class="card-title" id="explain-form-title" style="font-size: 15px;">Input Vulnerability Instance</h3>
                    <p id="explain-form-subtitle" style="font-size: 12px; color: var(--text-secondary); margin-top: 2px;">
                        Provide vulnerability text and weaknesses to decompose model decision pathways.
                    </p>
                </div>

                <div class="form-group" style="margin-bottom: 16px;">
                    <label class="form-label" for="explain-desc">Description Text <span style="color: var(--accent-scarlet);">*</span></label>
                    <textarea id="explain-desc" class="form-textarea" rows="4">An unauthenticated remote code execution vulnerability in Apache Log4j2 JNDI feature allows full system takeover.</textarea>
                    <span class="form-hint">Text passed to inductive TF-IDF feature pipeline.</span>
                </div>

                <div class="form-group" style="margin-bottom: 22px;">
                    <label class="form-label" for="explain-cwes">Associated CWE Identifiers</label>
                    <input type="text" id="explain-cwes" class="form-input" value="CWE-502, CWE-400">
                    <span class="form-hint">Comma-separated weakness identifiers.</span>
                </div>

                <button class="btn btn-primary" id="btn-run-explain" type="button" style="width: 100%; justify-content: center; height: 38px;">
                    Compute TreeExplainer Attributions
                </button>
            </div>

            <!-- Explanation Output Card -->
            <div>
                <div class="card" id="explanation-result-card" style="margin-bottom: 20px;">
                    <div class="card-header" style="padding-bottom: 12px; margin-bottom: 16px; border-bottom: 1px solid var(--border-subtle); display: flex; justify-content: space-between; align-items: center;">
                        <h3 class="card-title" style="font-size: 15px; margin: 0;">Feature Contributions</h3>
                        <span id="explain-model-badge" style="font-family: var(--font-mono); font-size: 11px; color: var(--text-muted);">EXP-A1</span>
                    </div>

                    <div id="explain-output-container">
                        <div class="empty-state" style="padding: 48px 24px;">
                            <div style="font-family: var(--font-mono); font-size: 12px; color: var(--text-muted); margin-bottom: 8px;">AWAITING COMPUTATION</div>
                            <p style="margin: 0; font-size: 13px; color: var(--text-secondary); max-width: 320px; margin-left: auto; margin-right: auto;">
                                Submit disclosure description and CWE weaknesses to compute TreeExplainer Shapley values.
                            </p>
                        </div>
                    </div>
                </div>

                <!-- Causal Interpretation Caveat -->
                <div style="font-size: 11px; color: var(--text-muted); line-height: 1.5; border-left: 2px solid var(--border-strong); padding-left: 10px;">
                    <strong style="color: var(--text-secondary);">Empirical Association Note:</strong> SHAP values reflect additive contributions to the tree ensemble margin for this specific instance. They represent empirical feature associations captured from the training distribution, not causal mechanisms.
                </div>
            </div>
        </div>
    `;

    const tabCvss = containerEl.querySelector('#tab-explain-cvss');
    const tabKev = containerEl.querySelector('#tab-explain-kev');
    const formTitle = containerEl.querySelector('#explain-form-title');
    const formSubtitle = containerEl.querySelector('#explain-form-subtitle');
    const modelBadge = containerEl.querySelector('#explain-model-badge');
    const btnRun = containerEl.querySelector('#btn-run-explain');
    const outputContainer = containerEl.querySelector('#explain-output-container');

    let mode = 'cvss'; // 'cvss' | 'kev'

    tabCvss.addEventListener('click', () => {
        mode = 'cvss';
        tabCvss.classList.add('active');
        tabKev.classList.remove('active');
        formTitle.textContent = 'Input Vulnerability Instance (EXP-A1)';
        formSubtitle.textContent = 'Inspect feature attributions for pre-scoring CVSS estimation.';
        modelBadge.textContent = 'EXP-A1';
    });

    tabKev.addEventListener('click', () => {
        mode = 'kev';
        tabKev.classList.add('active');
        tabCvss.classList.remove('active');
        formTitle.textContent = 'Input Vulnerability Instance (EXP-B2)';
        formSubtitle.textContent = 'Inspect feature attributions for publication-time KEV risk prediction.';
        modelBadge.textContent = 'EXP-B2';
    });

    btnRun.addEventListener('click', async () => {
        if (!state.isAuthenticated()) {
            outputContainer.innerHTML = `
                <div style="background: var(--bg-muted); border: 1px solid var(--border-subtle); border-radius: var(--radius-sm); padding: 24px; text-align: center;">
                    <div style="font-family: var(--font-mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--accent-scarlet); margin-bottom: 6px;">AUTHENTICATION REQUIRED</div>
                    <p style="margin: 0 0 16px 0; font-size: 13px; color: var(--text-secondary);">
                        Please sign in with a registered analyst or researcher demonstration account to generate SHAP explanations.
                    </p>
                    <button class="btn btn-primary btn-sm" type="button" onclick="window.location.hash='login'">Sign In to Continue</button>
                </div>
            `;
            return;
        }

        const desc = containerEl.querySelector('#explain-desc').value.trim();
        const cwesRaw = containerEl.querySelector('#explain-cwes').value;
        const cweIds = cwesRaw.split(',').map(s => s.trim()).filter(Boolean);

        const payload = {
            description_en: desc,
            cwe_ids: cweIds,
            cpe_count: 5,
            cpe_part_a_count: 5,
            cpe_part_o_count: 0,
            cpe_part_h_count: 0,
            vendor_count: 1,
            product_count: 1,
            pub_month: 12
        };

        outputContainer.innerHTML = `
            <div style="padding: 48px 24px; text-align: center;">
                <span class="loading-spinner"></span>
                <p style="margin-top: 14px; font-size: 13px; color: var(--text-secondary);">Computing TreeExplainer Shapley values for ${mode.toUpperCase()} model...</p>
            </div>
        `;

        try {
            const res = mode === 'cvss' ? await api.explainCVSS(payload) : await api.explainKEV(payload);
            renderShapResult(outputContainer, res);
        } catch (err) {
            if (err.status === 503 || err.message.includes('503') || err.message.includes('not loaded')) {
                outputContainer.innerHTML = `
                    <div style="background: var(--bg-muted); border: 1px solid var(--border-strong); border-radius: var(--radius-sm); padding: 20px; text-align: center;">
                        <div style="font-family: var(--font-mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--text-muted); margin-bottom: 6px;">ARTIFACT NOT LOADED</div>
                        <div style="font-size: 13px; color: var(--text-secondary);">${escapeHtml(err.message)}</div>
                    </div>
                `;
            } else {
                outputContainer.innerHTML = `
                    <div style="background: var(--bg-muted); border: 1px solid var(--accent-scarlet); border-radius: var(--radius-sm); padding: 16px;">
                        <div style="font-family: var(--font-mono); font-size: 12px; font-weight: 600; color: var(--accent-scarlet);">EXPLANATION ERROR</div>
                        <div style="margin-top: 6px; font-size: 13px; color: var(--text-primary); line-height: 1.5;">${escapeHtml(err.message)}</div>
                    </div>
                `;
            }
        }
    });
}

function renderShapResult(containerEl, res) {
    const items = res.top_feature_contributions || [];
    const maxAbs = items.length > 0 ? Math.max(...items.map(i => i.abs_shap_value)) : 1.0;

    const barsHtml = items.map(item => {
        const widthPct = Math.min(100, Math.max(4, (item.abs_shap_value / maxAbs) * 100));
        const isPos = item.shap_value >= 0;
        const barClass = isPos ? 'shap-bar-fill-pos' : 'shap-bar-fill-neg';
        const sign = isPos ? '+' : '';
        const valColor = isPos ? 'var(--shap-pos)' : 'var(--shap-neg)';

        return `
            <div class="shap-item">
                <div class="shap-feature-name" title="${escapeHtml(item.feature_name)}">${escapeHtml(item.feature_name)}</div>
                <div class="shap-bar-track">
                    <div class="${barClass}" style="width: ${widthPct.toFixed(1)}%;"></div>
                </div>
                <div class="shap-val-text" style="color: ${valColor}; font-weight: 600;">
                    ${sign}${item.shap_value.toFixed(4)}
                </div>
            </div>
        `;
    }).join('');

    containerEl.innerHTML = `
        <!-- Meta Summary -->
        <div style="background: var(--bg-muted); border: 1px solid var(--border-subtle); border-radius: var(--radius-sm); padding: 12px 14px; margin-bottom: 16px; font-size: 12px;">
            <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
                <span style="color: var(--text-secondary);">Target Model:</span>
                <span style="font-family: var(--font-mono); font-weight: 600; color: var(--text-primary);">${escapeHtml(res.target_model)}</span>
            </div>
            <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
                <span style="color: var(--text-secondary);">Expected Base Value:</span>
                <span style="font-family: var(--font-mono); color: var(--text-primary);">${res.base_value}</span>
            </div>
            <div style="display: flex; justify-content: space-between;">
                <span style="color: var(--text-secondary);">Final Prediction Output:</span>
                <span style="font-family: var(--font-mono); font-weight: 700; color: var(--accent-scarlet);">${res.predicted_value}</span>
            </div>
        </div>

        <!-- Legend -->
        <div class="shap-legend" style="margin-bottom: 14px;">
            <div class="shap-legend-item">
                <span class="shap-legend-dot" style="background: var(--shap-pos);"></span>
                <span>[+] Increases predicted risk / score</span>
            </div>
            <div class="shap-legend-item">
                <span class="shap-legend-dot" style="background: var(--shap-neg);"></span>
                <span>[-] Decreases predicted risk / score</span>
            </div>
        </div>

        <!-- Waterfall Bars -->
        <div class="shap-bar-container">
            ${barsHtml}
        </div>
    `;
}

function escapeHtml(str) {
    if (!str) return '';
    return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
